### ISSUE TITLE
Serialization of SPDX 3.0 Elements

### ISSUE THREAD

**Issue by jfuegen-metaeffekt** [spdx/spdx-java-jackson-store#73]
I am currently working with the new alpha release of the spdx-java-library and trying to serialize a MultiFormatStore containing multiple SPDX 3.0 Elements. 

I was wondering if it is already possible to use the JacksonSerializer to serialize a store not containing an SpdxDocument from the v2 library as the serialize() method seems to specifically look for spdx elements of the type "SpdxDocument" from my understanding. 

Currently trying to serialize spdx 3.0 elements simply results in an empty output-file. Just wondering if it is an issue with the Serializer or my implementation specifically.

**Comment by goneall** [comment]
@jfuegen-metaeffekt - Thanks for trying out the new alpha release.

There is a separate store specifically for SPDX 3.0 - the [spdx-java-v3jsonld-store](https://github.com/spdx/spdx-java-v3jsonld-store).  If you switch over to that library, it should work.

I would have expected some type of error rather than an empty output file - I'll have to look into the error handling.

**Comment by jfuegen-metaeffekt** [comment]
Thank you for the quick reply.

I tried out the new library and it seems to work flawlessly so far.

**Comment by goneall** [comment]
> I tried out the new library and it seems to work flawlessly so far.

Great!  I'll leave this issue open to track improving the error handling.
